/**
 * Master Data registry — Companies and Sectors.
 * Destination: src/lib/masterData.ts
 *
 * ══════════════════════════════════════════════════════════════════════
 * WHY THIS FILE EXISTS  (Phase 3F, repairing Phase 3E)
 *
 * Phase 3E found two structural breaks:
 *
 *   CRIT-3E-02  Company edits were written to `pactum-enterprise-companies`
 *               but only ONE page read that key. Twelve other consumers
 *               imported the static `MOCK_COMPANIES` array directly, so a
 *               rename was visible on exactly one screen.
 *
 *   CRIT-3E-04  Sectors had no CRUD at all. They lived in `mock/sectors.ts`
 *               with no writer, which also made it impossible to attach a
 *               newly created project to anything.
 *
 * This module becomes the SINGLE SOURCE OF TRUTH for both. The mock files
 * are demoted to first-run SEED DATA and are never written to.
 *
 * ── Why the mock modules are injected rather than imported ────────────
 *
 *   `mock/companies.ts` and `mock/sectors.ts` are not owned by this layer
 *   and are not modified by this phase. Importing them here would create a
 *   hard dependency in the opposite direction to the one we want, and would
 *   make this module untestable outside the app. Instead the app calls
 *   `seedMasterData()` once at start-up with whatever the mocks hold. If it
 *   is never called, the store simply starts empty — no crash, no guess.
 *
 * ── Relationship model (locked by the Phase 3F brief) ─────────────────
 *
 *   Company 1──n Sector 1──n Project
 *
 *   The brief states "Project creation requires Company, Sector". A project
 *   must therefore CARRY its parents. `Project.companyId` / `Project.sectorId`
 *   are the authoritative link (see `lib/data.ts`).
 *
 *   `Sector.projectIds` is RETAINED as a derived cache so the 13 existing
 *   reverse-lookup call sites keep working unchanged, but it is no longer
 *   the source of truth. `reconcile()` rebuilds it from the projects array.
 *   Where the two disagree, the project wins — it is the record that a human
 *   actually filled in.
 *
 * ── What this file does NOT do ────────────────────────────────────────
 *
 *   No money, no dates, no calculation. It stores names and parentage and
 *   refuses operations that would break referential integrity.
 * ══════════════════════════════════════════════════════════════════════
 */

const COMPANIES_KEY = 'pactum-enterprise-companies';
const SECTORS_KEY = 'pactum-enterprise-sectors';

// ── Shapes ─────────────────────────────────────────────────────────────
//
// Field names mirror exactly what the existing UI already reads, so no
// consumer needs to change: c.id · c.name · c.country · c.city · c.logoUrl
// · c.status · c.portfolioValue · c.sectors · c.projects
// and s.id · s.name · s.companyId · s.projectIds · s.status

export type EntityStatus = 'Active' | 'Paused' | 'Archived';

/**
 * Working-week calendars.
 *
 * DELIBERATELY NOT USED BY ANY CALCULATION. The Delay engine counts
 * calendar days and the EVM engine works from the project programme;
 * neither consults this. It is recorded so a company's working week is
 * documented, and so a future scheduling feature has somewhere to read it
 * from. Wiring it into Delay or EVM would change historical numbers.
 */
export type CalendarKind =
  | 'gregorian-5day'   // Mon-Fri
  | 'gregorian-6day'   // Mon-Sat
  | 'gulf-sun-thu'     // Sun-Thu
  | 'gulf-sat-thu'     // Sat-Thu
  | 'continuous';      // 7 days

export const CALENDARS: { value: CalendarKind; en: string; ar: string }[] = [
  { value: 'gulf-sun-thu',    en: 'Sunday - Thursday',  ar: 'الأحد - الخميس' },
  { value: 'gulf-sat-thu',    en: 'Saturday - Thursday', ar: 'السبت - الخميس' },
  { value: 'gregorian-5day',  en: 'Monday - Friday',    ar: 'الاثنين - الجمعة' },
  { value: 'gregorian-6day',  en: 'Monday - Saturday',  ar: 'الاثنين - السبت' },
  { value: 'continuous',      en: 'Continuous (7 days)', ar: 'مستمر (7 أيام)' },
];

export type RiskRating = 'Low' | 'Medium' | 'High' | 'Critical';
export type Compliance = 'Compliant' | 'Non-compliant' | 'Partial';

/**
 * Field-for-field compatible with the original `mock/companies.ts` shape,
 * so `CompanyCard`, `CompanyGrid` and every page keep compiling unchanged.
 * `nameAr` / `createdAt` / `createdBy` are additive.
 */
export interface Company {
  id: string;
  /** User-entered. NEVER autogenerated — see `createCompany`. */
  name: string;
  nameAr?: string;
  logoUrl?: string;
  status: EntityStatus;
  portfolioValue: number;

  /**
   * Branding and free text owned by the Company Management modal.
   *
   * PHASE 3I: the modal edits these four; before they were declared here,
   * `cleanCompany` rebuilt each record field-by-field and dropped anything
   * it did not recognise. A user could type a description, press Save, see
   * the modal close, and lose the text with no error. Verified by
   * execution, then closed.
   */
  description?: string;
  primaryColor?: string;
  secondaryColor?: string;
  /** Derived counts, refreshed by `reconcile()`. Never authoritative. */
  sectors: number;
  projects: number;
  riskRating: RiskRating;
  compliance: Compliance;
  /** Required by the original interface. */
  country: string;
  city?: string;
  headquarters?: string;

  /**
   * PHASE 3F Task 4 — REPORTING CURRENCY BELONGS ONLY TO THE COMPANY.
   *
   * The authority remains `pactum-currency-{companyId}.baseCurrency`,
   * which the FX engine owns and every conversion already reads. This
   * field is a MIRROR kept in step by `setReportingCurrency()` so the
   * company record is self-describing — a list of companies can show the
   * currency without opening the FX store for each row.
   *
   * Never write it directly. `reportingCurrencyOf()` reads the FX store,
   * not this, so the two can never diverge in a way that changes a number.
   */
  reportingCurrency?: string;

  /** IANA zone, e.g. `Asia/Riyadh`. Presentation only — no calculation. */
  timeZone?: string;
  /** Working-week calendar. Presentation and planning only. */
  calendar?: CalendarKind;

  createdAt: string;
  createdBy: string;
}

export interface Sector {
  id: string;
  /** User-entered. NEVER autogenerated. */
  name: string;
  nameAr?: string;
  companyId: string;
  status: EntityStatus;

  /**
   * Archive audit. The sector could be archived and restored, but neither
   * act left any trace — no time, no actor, no history. These record it.
   *
   * `archivedAt` / `archivedBy` describe the CURRENT archived state and
   * are cleared on restore. `archiveLog` is APPEND-ONLY and survives
   * every restore, so the fact that a sector was once archived can never
   * be erased by un-archiving it.
   */
  archivedAt?: string;
  archivedBy?: string;
  archiveLog?: { action: 'archived' | 'restored'; at: string; by: string; note: string }[];
  /**
   * DERIVED CACHE. Rebuilt from `Project.sectorId` by `reconcile()`.
   * Retained so the existing `sector.projectIds.includes(id)` call sites
   * continue to work without modification.
   */
  projectIds: string[];
  /** Display order within the parent company. Contiguous from 0. */
  order: number;

  /**
   * Task 4 — OPTIONAL default contract currency for new projects here.
   *
   * Empty means "inherit the company's reporting currency". It is a
   * DEFAULT for the create-project form, never a conversion input: once a
   * project is created its own contract currency governs, and changing
   * this later cannot restate a project that already exists.
   */
  defaultContractCurrency?: string;

  /**
   * The currency THIS SECTOR's own analytics are expressed in.
   *
   * ══════════════════════════════════════════════════════════════════
   * DISTINCT FROM `defaultContractCurrency` ABOVE, WHICH IS NOT A UNIT.
   *
   *   defaultContractCurrency  a pre-fill for the create-project form.
   *                            Never used to display or convert anything.
   *   reportingCurrency        the unit every figure on the sector's own
   *                            screens is converted into and shown in.
   *
   * The two were conflated before this field existed, which is why a
   * sector had no way to state the currency it reports in — it only had
   * a hint for a form it may never open.
   *
   * MANDATORY on creation. Absent on sectors created before the field
   * existed; `scopeCurrency()` reports that as unset rather than
   * silently substituting the company's, so a screen can ask for a
   * decision instead of inventing one.
   * ══════════════════════════════════════════════════════════════════
   */
  reportingCurrency?: string;

  createdAt: string;
  createdBy: string;
}

/** The minimum a project must expose for reconciliation. */
export interface ProjectLink {
  id: string;
  companyId?: string;
  sectorId?: string;
  /**
   * SPRINT 2 — required by the archive guards.
   *
   * Without it `archiveSector` cannot distinguish a live project from an
   * archived one, so it counted every project as a blocker and archiving
   * was impossible even after the projects had been archived. Optional so
   * every existing caller still compiles; absent is treated as active,
   * which is the safe reading.
   */
  status?: string;
}

// ── Result type ────────────────────────────────────────────────────────
//
// Every mutator returns the same envelope. `ok:false` always carries a
// machine-readable `reason` AND a `blockers` list when the refusal is
// caused by dependent records — the UI needs to name them, not just say no.

export type MdReason =
  | 'missing-name'
  | 'duplicate-name'
  | 'duplicate-id'
  | 'not-found'
  | 'missing-company'
  | 'company-not-found'
  | 'has-dependents'
  | 'invalid-order'
  | 'missing-currency'
  | 'invalid-currency'
  /** SPRINT 2 — archive guards. */
  | 'already-archived'
  | 'not-archived'
  | 'has-active-children';

export interface MdResult<T> {
  ok: boolean;
  reason?: MdReason;
  record?: T;
  /** Human-readable dependents that blocked a delete. */
  blockers?: string[];
}

// ── Storage ────────────────────────────────────────────────────────────

function readJson<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return fallback;
    const parsed = JSON.parse(raw);
    return parsed ?? fallback;
  } catch {
    return fallback;
  }
}

function writeJson(key: string, value: unknown): void {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch {
    /* quota — same policy as every other store in the platform */
  }
}

const nowIso = () => new Date().toISOString();

/**
 * Id generator.
 *
 * Prefixed and time-ordered so two ids minted in the same millisecond still
 * differ by their random tail, and so an id is recognisable in storage.
 * `createCompany`/`createSector` additionally REJECT a collision rather than
 * trusting this to be unique — see the duplicate-id guard.
 */
function mintId(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

/** Case-insensitive, whitespace-insensitive name comparison. */
function sameName(a: string, b: string): boolean {
  return a.trim().toLowerCase() === b.trim().toLowerCase();
}

// ── Normalisation ──────────────────────────────────────────────────────
//
// Anything read from storage is coerced into shape. A hand-edited or
// half-migrated record can never crash a consumer.

const RISKS: RiskRating[] = ['Low', 'Medium', 'High', 'Critical'];
const COMPLIANCES: Compliance[] = ['Compliant', 'Non-compliant', 'Partial'];

function cleanCompany(v: any): Company | null {
  const id = String(v?.id ?? '').trim();
  const name = String(v?.name ?? '').trim();
  if (!id || !name) return null;
  const status = (['Active', 'Paused', 'Archived'] as const)
    .includes(v?.status) ? v.status as EntityStatus : 'Active';
  return {
    id,
    name,
    nameAr: v?.nameAr ? String(v.nameAr) : undefined,
    logoUrl: v?.logoUrl ? String(v.logoUrl) : undefined,
    status,
    portfolioValue: Number.isFinite(Number(v?.portfolioValue))
      ? Number(v.portfolioValue) : 0,
    sectors: Number(v?.sectors) || 0,
    projects: Number(v?.projects) || 0,
    riskRating: RISKS.includes(v?.riskRating) ? v.riskRating : 'Low',
    compliance: COMPLIANCES.includes(v?.compliance) ? v.compliance : 'Compliant',
    // Modal-owned branding. Preserved rather than dropped.
    description: v?.description ? String(v.description) : undefined,
    primaryColor: v?.primaryColor ? String(v.primaryColor) : undefined,
    secondaryColor: v?.secondaryColor ? String(v.secondaryColor) : undefined,
    // `country` is REQUIRED by the original interface. Empty string rather
    // than a guessed country — an invented location is worse than a blank.
    country: String(v?.country ?? ''),
    city: v?.city ? String(v.city) : undefined,
    headquarters: v?.headquarters ? String(v.headquarters) : undefined,
    reportingCurrency: v?.reportingCurrency
      ? String(v.reportingCurrency).toUpperCase().slice(0, 3) : undefined,
    timeZone: v?.timeZone ? String(v.timeZone) : undefined,
    calendar: CALENDARS.some(c => c.value === v?.calendar) ? v.calendar : undefined,
    createdAt: String(v?.createdAt ?? ''),
    createdBy: String(v?.createdBy ?? ''),
  };
}

function cleanSector(v: any, fallbackOrder: number): Sector | null {
  const id = String(v?.id ?? '').trim();
  const name = String(v?.name ?? '').trim();
  const companyId = String(v?.companyId ?? '').trim();
  if (!id || !name || !companyId) return null;
  const status = (['Active', 'Paused', 'Archived'] as const)
    .includes(v?.status) ? v.status as EntityStatus : 'Active';
  return {
    id,
    name,
    nameAr: v?.nameAr ? String(v.nameAr) : undefined,
    companyId,
    status,
    /**
     * The archive audit must survive the read. `cleanSector` rebuilds the
     * object field by field, so anything not named here is DROPPED — the
     * log would have been erased on the next load, which is the one thing
     * an append-only record must never do.
     */
    archivedAt: v?.archivedAt ? String(v.archivedAt) : undefined,
    archivedBy: v?.archivedBy ? String(v.archivedBy) : undefined,
    archiveLog: Array.isArray(v?.archiveLog)
      ? v.archiveLog
          .filter((e: any) => e && (e.action === 'archived' || e.action === 'restored'))
          .map((e: any) => ({
            action: e.action as 'archived' | 'restored',
            at: String(e.at ?? ''),
            by: String(e.by ?? 'unknown'),
            note: String(e.note ?? ''),
          }))
      : undefined,
    projectIds: Array.isArray(v?.projectIds) ? v.projectIds.map(String) : [],
    order: Number.isFinite(Number(v?.order)) ? Number(v.order) : fallbackOrder,
    defaultContractCurrency: v?.defaultContractCurrency
      ? String(v.defaultContractCurrency).toUpperCase().slice(0, 3) : undefined,
    reportingCurrency: v?.reportingCurrency
      ? String(v.reportingCurrency).toUpperCase().slice(0, 3) : undefined,
    createdAt: String(v?.createdAt ?? ''),
    createdBy: String(v?.createdBy ?? ''),
  };
}

// ── Readers ────────────────────────────────────────────────────────────

export function readCompanies(): Company[] {
  const raw = readJson<any[]>(COMPANIES_KEY, []);
  if (!Array.isArray(raw)) return [];
  return raw.map(cleanCompany).filter((x): x is Company => x !== null);
}

export function readSectors(): Sector[] {
  const raw = readJson<any[]>(SECTORS_KEY, []);
  if (!Array.isArray(raw)) return [];
  const out = raw
    .map((v, i) => cleanSector(v, i))
    .filter((x): x is Sector => x !== null);
  // Stable presentation order: by company, then by explicit order.
  return out.sort((a, b) =>
    a.companyId.localeCompare(b.companyId) || a.order - b.order);
}

// ── Reactivity ─────────────────────────────────────────────────────────
//
// PHASE 3F-UX · Task 2.
//
// Phase 3E found master data correct on disk but STALE on any page that
// was already mounted: a company rename showed on the page that made it
// and nowhere else until remount. `useProjects` had solved this properly
// with a module-level subscriber Set; master data had not.
//
// The mechanism is deliberately identical to the one already proven in
// `store.ts` — same shape, same unmount safety — rather than a second
// invented pattern. Every write in this module already funnels through
// `writeCompanies` / `writeSectors`, so notification is added at that one
// choke point and NO mutator changes. That is why the 14 call sites above
// are untouched.

type MdListener = () => void;
const listeners = new Set<MdListener>();

/**
 * Registers a listener, returns its unsubscribe.
 *
 * Version-based rather than value-based: master data is read through
 * `findCompanyById` / `fetchSectors` etc., which hit localStorage on every
 * call. Pushing a value would mean choosing WHICH of the eight readers to
 * push, so instead the listener is simply told "something changed" and
 * re-reads whatever it needs.
 */
export function subscribeMasterData(fn: MdListener): () => void {
  listeners.add(fn);
  return () => { listeners.delete(fn); };
}

/** Bumped on every committed write. The value a hook renders against. */
let mdVersion = 0;
export function masterDataVersion(): number { return mdVersion; }

function notifyMasterData(): void {
  mdVersion++;
  // Copy before iterating: a listener may unmount during the notify pass.
  Array.from(listeners).forEach(fn => {
    try { fn(); } catch { /* one bad listener must not stop the rest */ }
  });
}

/** Test hook. Not used by the app. */
export function resetMasterDataListeners(): void {
  listeners.clear();
  mdVersion = 0;
}

function writeCompanies(list: Company[]): void {
  writeJson(COMPANIES_KEY, list);
  notifyMasterData();
}

function writeSectors(list: Sector[]): void {
  writeJson(SECTORS_KEY, list);
  notifyMasterData();
}

// ── Lookups (drop-in replacements for the mock helpers) ────────────────

export function findCompanyById(id: string): Company | undefined {
  if (!id) return undefined;
  return readCompanies().find(c => c.id === id);
}

export function findSectorById(id: string): Sector | undefined {
  if (!id) return undefined;
  return readSectors().find(s => s.id === id);
}

export function findSectorsByCompany(companyId: string): Sector[] {
  if (!companyId) return [];
  return readSectors()
    .filter(s => s.companyId === companyId)
    .sort((a, b) => a.order - b.order);
}

/** Every sector, ordered. Drop-in for `fetchSectors()`. */
export function fetchSectors(): Sector[] {
  return readSectors();
}

/** Every company, ordered by name. */
export function fetchCompanies(): Company[] {
  return readCompanies().sort((a, b) => a.name.localeCompare(b.name));
}

// ── Seeding ────────────────────────────────────────────────────────────

/**
 * First-run seed from the mock modules.
 *
 * NON-DESTRUCTIVE and IDEMPOTENT. A key that already holds data is left
 * exactly as it is, so a user's edits are never overwritten by a page
 * reload. Safe to call on every start-up.
 *
 * @returns what was seeded, for logging only.
 */
export function seedMasterData(
  companies: any[], sectors: any[],
): { companies: number; sectors: number } {
  let seededCompanies = 0;
  let seededSectors = 0;

  // An EMPTY seed must not claim the slot.
  //
  // `mock/companies.fetchCompanies()` self-seeds with `(MOCK_COMPANIES, [])`
  // because it cannot import MOCK_SECTORS without a circular dependency.
  // Writing that `[]` would mark sectors as "already seeded" and the real
  // sector seed arriving moments later would be skipped — leaving a company
  // list with no sectors under it. Seeding nothing is not seeding.
  if (localStorage.getItem(COMPANIES_KEY) === null
      && Array.isArray(companies) && companies.length > 0) {
    const list = companies
      .map(c => cleanCompany({ ...c, createdAt: c?.createdAt || nowIso(), createdBy: c?.createdBy || 'seed' }))
      .filter((x): x is Company => x !== null);
    writeCompanies(list);
    seededCompanies = list.length;

    // A seeded company predates the mandatory-reporting-currency rule, so
    // it carries neither the field nor an FX settings entry. Without one,
    // `reportingCurrencyOfCompany` correctly returns '' — and a create
    // form would then offer a blank inherited currency.
    //
    // Backfilled to SAR, which is what these records ALWAYS implicitly
    // were: every seeded figure was captured in the platform base before
    // multi-currency existed. This states that fact rather than inventing
    // one, and it runs only on the first-ever seed.
    list.forEach(c => {
      if (!c.reportingCurrency) ensureReportingCurrency(c.id, 'SAR');
    });
  }

  if (localStorage.getItem(SECTORS_KEY) === null
      && Array.isArray(sectors) && sectors.length > 0) {
    // Order is assigned per company in the order the seed presents them.
    const perCompany = new Map<string, number>();
    const list = sectors
      .map(s => {
        const cid = String(s?.companyId ?? '');
        const n = perCompany.get(cid) ?? 0;
        perCompany.set(cid, n + 1);
        return cleanSector(
          { ...s, order: s?.order ?? n, createdAt: s?.createdAt || nowIso(), createdBy: s?.createdBy || 'seed' },
          n,
        );
      })
      .filter((x): x is Sector => x !== null);
    writeSectors(list);
    seededSectors = list.length;
  }

  return { companies: seededCompanies, sectors: seededSectors };
}

// ── COMPANY CRUD ───────────────────────────────────────────────────────

export interface CreateCompanyInput {
  name: string;
  nameAr?: string;
  country?: string;
  city?: string;
  headquarters?: string;
  logoUrl?: string;
  status?: EntityStatus;
  portfolioValue?: number;
  riskRating?: RiskRating;
  compliance?: Compliance;
  /** Modal-owned branding. */
  description?: string;
  primaryColor?: string;
  secondaryColor?: string;
  /** Task 4. MANDATORY at creation — see `createCompany`. */
  reportingCurrency?: string;
  timeZone?: string;
  calendar?: CalendarKind;
  createdBy?: string;
  /** Optional explicit id, for import. Rejected if already taken. */
  id?: string;
}

/**
 * Creates a company.
 *
 * NO AUTOGENERATED NAMES. An empty or whitespace-only name is refused
 * outright rather than being replaced with "Company 4" or "Untitled" —
 * a placeholder name is indistinguishable from a real one three months
 * later, and the Phase 3E brief calls this out explicitly.
 */
export function createCompany(input: CreateCompanyInput): MdResult<Company> {
  const list = readCompanies();
  const name = (input.name ?? '').trim();

  if (!name) return { ok: false, reason: 'missing-name' };
  if (list.some(c => sameName(c.name, name))) {
    return { ok: false, reason: 'duplicate-name' };
  }

  // Task 4 — REPORTING CURRENCY IS MANDATORY.
  //
  // A company with no reporting currency cannot be reported on at all:
  // every conversion resolves against it. Defaulting it silently is what
  // produced the wrong-SAR class of defect, so it is refused instead.
  const rc = (input.reportingCurrency ?? '').trim().toUpperCase();
  if (!rc) return { ok: false, reason: 'missing-currency' };
  if (!/^[A-Z]{3}$/.test(rc)) return { ok: false, reason: 'invalid-currency' };

  const id = (input.id ?? '').trim() || mintId('co');
  if (list.some(c => c.id === id)) return { ok: false, reason: 'duplicate-id' };

  const record: Company = {
    id,
    name,
    nameAr: input.nameAr?.trim() || undefined,
    logoUrl: input.logoUrl || undefined,
    status: input.status ?? 'Active',
    portfolioValue: Number(input.portfolioValue) || 0,
    sectors: 0,
    projects: 0,
    riskRating: input.riskRating ?? 'Low',
    compliance: input.compliance ?? 'Compliant',
    description: input.description?.trim() || undefined,
    primaryColor: input.primaryColor || undefined,
    secondaryColor: input.secondaryColor || undefined,
    reportingCurrency: rc,
    timeZone: input.timeZone?.trim() || undefined,
    calendar: input.calendar,
    country: input.country?.trim() ?? '',
    city: input.city?.trim() || undefined,
    headquarters: input.headquarters?.trim() || undefined,
    createdAt: nowIso(),
    createdBy: input.createdBy || 'unknown',
  };

  writeCompanies([...list, record]);
  // Keep the FX store — the AUTHORITY — in step from the first moment.
  writeReportingCurrencyToFx(id, rc);
  return { ok: true, record };
}

/**
 * Writes `baseCurrency` into the company's FX settings.
 *
 * The FX store is the authority every conversion reads; the field on the
 * Company record is only a mirror for display. This helper is the single
 * place the two are synchronised, so they cannot drift.
 *
 * It touches ONLY `baseCurrency` — the supported-currency list and every
 * published rate are preserved exactly as found. No rate is created,
 * altered or removed, and no historical figure changes.
 */
/**
 * Gives a company a reporting currency ONLY when it has none.
 *
 * Never overwrites: a company that already declares one keeps it, so this
 * is safe to call on every start-up and cannot restate a live setting.
 */
function ensureReportingCurrency(companyId: string, fallback: string): void {
  const existing = (() => {
    try {
      const raw = JSON.parse(localStorage.getItem(`pactum-currency-${companyId}`) || 'null');
      return String(raw?.baseCurrency ?? '').toUpperCase().slice(0, 3);
    } catch { return ''; }
  })();
  const code = existing || fallback;

  const list = readCompanies();
  const i = list.findIndex(c => c.id === companyId);
  if (i >= 0 && !list[i].reportingCurrency) {
    const out = list.slice();
    out[i] = { ...out[i], reportingCurrency: code };
    writeJson(COMPANIES_KEY, out);   // no notify: seeding, not a user edit
  }
  if (!existing) writeReportingCurrencyToFx(companyId, code);
}

function writeReportingCurrencyToFx(companyId: string, code: string): void {
  try {
    const key = `pactum-currency-${companyId}`;
    const raw = JSON.parse(localStorage.getItem(key) || 'null');
    const next = (raw && typeof raw === 'object')
      ? { ...raw, baseCurrency: code }
      : { baseCurrency: code, currencies: [] };
    localStorage.setItem(key, JSON.stringify(next));
  } catch { /* quota — the mirror on the record still records intent */ }
}

/**
 * Sets a company's reporting currency — Task 4.
 *
 * FORWARD-LOOKING ONLY. Not one stored amount is rewritten: every
 * historical figure keeps the `appliedRate` frozen at the moment it was
 * captured, and every approved Timeline snapshot keeps the reporting
 * currency it was archived under. Changing this alters what FUTURE
 * reporting converts into, and nothing else — which is exactly what the
 * brief requires.
 */
export function setReportingCurrency(
  companyId: string, code: string,
): MdResult<Company> {
  const list = readCompanies();
  const i = list.findIndex(c => c.id === companyId);
  if (i < 0) return { ok: false, reason: 'not-found' };

  const rc = (code || '').trim().toUpperCase();
  if (!rc) return { ok: false, reason: 'missing-currency' };
  if (!/^[A-Z]{3}$/.test(rc)) return { ok: false, reason: 'invalid-currency' };

  const next: Company = { ...list[i], reportingCurrency: rc };
  const out = list.slice();
  out[i] = next;
  writeCompanies(out);
  writeReportingCurrencyToFx(companyId, rc);
  return { ok: true, record: next };
}

export type UpdateCompanyInput = Partial<Omit<Company, 'id' | 'createdAt' | 'createdBy'>>;

/**
 * Renames / edits a company.
 *
 * Because every consumer now reads this store, a rename here IS the
 * propagation — there is no second copy to keep in step.
 */
export function updateCompany(id: string, patch: UpdateCompanyInput): MdResult<Company> {
  const list = readCompanies();
  const i = list.findIndex(c => c.id === id);
  if (i < 0) return { ok: false, reason: 'not-found' };

  if (patch.name !== undefined) {
    const name = patch.name.trim();
    if (!name) return { ok: false, reason: 'missing-name' };
    if (list.some(c => c.id !== id && sameName(c.name, name))) {
      return { ok: false, reason: 'duplicate-name' };
    }
  }

  const next: Company = {
    ...list[i],
    ...patch,
    name: patch.name !== undefined ? patch.name.trim() : list[i].name,
    id: list[i].id,
    createdAt: list[i].createdAt,
    createdBy: list[i].createdBy,
  };

  const out = list.slice();
  out[i] = next;
  writeCompanies(out);
  return { ok: true, record: next };
}

/**
 * Archives a company.
 *
 * ══════════════════════════════════════════════════════════════════════
 * SPRINT 2 — ARCHIVE IS NOT DELETE
 *
 * `EntityStatus` already carried 'Archived' and `deleteCompany` already
 * refused while dependents existed — but nothing could actually MOVE a
 * company into the archived state. The status was declared and
 * unreachable.
 *
 * Archiving is the answer to "I cannot delete this because it has
 * sectors, but I do not want to see it any more". So unlike delete it is
 * ALLOWED with children: the whole point is to retire a company whose
 * history must stay readable.
 *
 * What it refuses is archiving a company that still has ACTIVE sectors,
 * because that would hide a parent while its children stay live in
 * pickers — the user would see orphan-looking sectors with no company.
 * Archive the sectors first, or use `cascade` to archive them together.
 *
 * Nothing is deleted. No storage key is touched. Reversible via
 * `restoreCompany`.
 * ══════════════════════════════════════════════════════════════════════
 */
export function archiveCompany(
  id: string, by = 'unknown', opts: { cascade?: boolean } = {},
): MdResult<Company> {
  const list = readCompanies();
  const i = list.findIndex(c => c.id === id);
  if (i < 0) return { ok: false, reason: 'not-found' };
  if (list[i].status === 'Archived') {
    return { ok: false, reason: 'already-archived', record: list[i] };
  }

  const sectors = readSectors().filter(s => s.companyId === id);
  const activeSectors = sectors.filter(s => s.status !== 'Archived');

  if (activeSectors.length > 0 && !opts.cascade) {
    return {
      ok: false,
      reason: 'has-active-children',
      blockers: [`${activeSectors.length} active sector(s): ${activeSectors.map(s => s.name).join(', ')}`],
    };
  }

  // Cascade: children first, so a failure part-way cannot leave an
  // archived parent above live children.
  if (opts.cascade && activeSectors.length > 0) {
    const all = readSectors();
    writeSectors(all.map(s =>
      s.companyId === id && s.status !== 'Archived'
        ? { ...s, status: 'Archived' as EntityStatus }
        : s));
  }

  const next: Company = { ...list[i], status: 'Archived' };
  const out = list.slice();
  out[i] = next;
  writeCompanies(out);
  return { ok: true, record: next };
}

/**
 * Restores an archived company to Active.
 *
 * Sectors are NOT restored with it. A cascade archive was a deliberate
 * bulk action; a cascade restore would silently revive sectors the user
 * may have archived individually beforehand, and there is no record of
 * which state each was in. They are restored one at a time, visibly.
 */
export function restoreCompany(id: string): MdResult<Company> {
  const list = readCompanies();
  const i = list.findIndex(c => c.id === id);
  if (i < 0) return { ok: false, reason: 'not-found' };
  if (list[i].status !== 'Archived') {
    return { ok: false, reason: 'not-archived', record: list[i] };
  }
  const next: Company = { ...list[i], status: 'Active' };
  const out = list.slice();
  out[i] = next;
  writeCompanies(out);
  return { ok: true, record: next };
}

/** Companies excluding archived — what every picker should show. */
export function activeCompanies(): Company[] {
  return readCompanies().filter(c => c.status !== 'Archived');
}

/**
 * Deletes a company — REFUSED while anything depends on it.
 *
 * Two levels are checked, because either one left behind would be an
 * orphan: the company's sectors, and any project pointing at the company
 * directly. The blockers are returned by name so the UI can tell the user
 * what to clear first instead of just refusing.
 */
export function deleteCompany(id: string, projects: ProjectLink[] = []): MdResult<Company> {
  const list = readCompanies();
  const target = list.find(c => c.id === id);
  if (!target) return { ok: false, reason: 'not-found' };

  const sectors = readSectors().filter(s => s.companyId === id);
  const directProjects = projects.filter(p => p.companyId === id);
  const sectorIds = new Set(sectors.map(s => s.id));
  const viaSector = projects.filter(p => p.sectorId && sectorIds.has(p.sectorId));

  const projectCount = new Set([
    ...directProjects.map(p => p.id),
    ...viaSector.map(p => p.id),
  ]).size;

  if (sectors.length > 0 || projectCount > 0) {
    const blockers: string[] = [];
    if (sectors.length) blockers.push(`${sectors.length} sector(s): ${sectors.map(s => s.name).join(', ')}`);
    if (projectCount) blockers.push(`${projectCount} project(s)`);
    return { ok: false, reason: 'has-dependents', blockers };
  }

  writeCompanies(list.filter(c => c.id !== id));
  return { ok: true, record: target };
}

// ── SECTOR CRUD ────────────────────────────────────────────────────────

export interface CreateSectorInput {
  name: string;
  nameAr?: string;
  companyId: string;
  /** Optional. Empty inherits the company reporting currency. */
  defaultContractCurrency?: string;
  /**
   * MANDATORY — the unit this sector's analytics are reported in.
   * A sector that cannot state its currency cannot state a total, so
   * creation is refused rather than defaulted.
   */
  reportingCurrency: string;
  status?: EntityStatus;
  createdBy?: string;
  id?: string;
}

/**
 * Creates a sector under a company.
 *
 * Duplicate names are refused WITHIN THE PARENT only — two different
 * companies may both have an "Infrastructure" sector, and refusing that
 * would be wrong. Uniqueness is scoped to where the ambiguity actually
 * exists.
 */
export function createSector(input: CreateSectorInput): MdResult<Sector> {
  const name = (input.name ?? '').trim();
  const companyId = (input.companyId ?? '').trim();

  if (!name) return { ok: false, reason: 'missing-name' };
  if (!companyId) return { ok: false, reason: 'missing-company' };
  if (!findCompanyById(companyId)) return { ok: false, reason: 'company-not-found' };

  // The reporting currency is mandatory: every figure on this sector's
  // screens is converted into it, and a missing unit is what produced
  // totals labelled with a currency nobody chose.
  const reportingCurrency = (input.reportingCurrency ?? '').trim().toUpperCase();
  if (!reportingCurrency) return { ok: false, reason: 'missing-currency' };
  if (!/^[A-Z]{3}$/.test(reportingCurrency)) {
    return { ok: false, reason: 'invalid-currency' };
  }

  const list = readSectors();
  const siblings = list.filter(s => s.companyId === companyId);
  if (siblings.some(s => sameName(s.name, name))) {
    return { ok: false, reason: 'duplicate-name' };
  }

  const id = (input.id ?? '').trim() || mintId('sec');
  if (list.some(s => s.id === id)) return { ok: false, reason: 'duplicate-id' };

  const record: Sector = {
    id,
    name,
    nameAr: input.nameAr?.trim() || undefined,
    companyId,
    status: input.status ?? 'Active',
    projectIds: [],
    defaultContractCurrency:
      (input.defaultContractCurrency ?? '').trim().toUpperCase() || undefined,
    reportingCurrency,
    // Appended to the end of its own company's list.
    order: siblings.length,
    createdAt: nowIso(),
    createdBy: input.createdBy || 'unknown',
  };

  writeSectors([...list, record]);
  return { ok: true, record };
}

export type UpdateSectorInput = Partial<
  Omit<Sector, 'id' | 'createdAt' | 'createdBy' | 'projectIds'>
>;

/**
 * Renames / edits a sector.
 *
 * Moving a sector to another company is permitted, but the duplicate-name
 * check then runs against the DESTINATION company's siblings — otherwise a
 * move could quietly create the collision that `createSector` refuses.
 */
export function updateSector(id: string, patch: UpdateSectorInput): MdResult<Sector> {
  const list = readSectors();
  const i = list.findIndex(s => s.id === id);
  if (i < 0) return { ok: false, reason: 'not-found' };

  const current = list[i];
  const destCompany = patch.companyId?.trim() || current.companyId;

  if (patch.companyId !== undefined && !findCompanyById(destCompany)) {
    return { ok: false, reason: 'company-not-found' };
  }

  if (patch.name !== undefined || patch.companyId !== undefined) {
    const name = (patch.name ?? current.name).trim();
    if (!name) return { ok: false, reason: 'missing-name' };
    const clash = list.some(s =>
      s.id !== id && s.companyId === destCompany && sameName(s.name, name));
    if (clash) return { ok: false, reason: 'duplicate-name' };
  }

  const next: Sector = {
    ...current,
    ...patch,
    name: patch.name !== undefined ? patch.name.trim() : current.name,
    companyId: destCompany,
    id: current.id,
    projectIds: current.projectIds,
    createdAt: current.createdAt,
    createdBy: current.createdBy,
  };

  const out = list.slice();
  out[i] = next;
  writeSectors(out);
  return { ok: true, record: next };
}

/**
 * Deletes a sector — REFUSED while any project belongs to it.
 *
 * Checked against the LIVE projects array rather than the cached
 * `projectIds`, because the cache is derived and could be stale. The
 * authoritative answer is "does a project point here right now".
 */
export function deleteSector(id: string, projects: ProjectLink[] = []): MdResult<Sector> {
  const list = readSectors();
  const target = list.find(s => s.id === id);
  if (!target) return { ok: false, reason: 'not-found' };

  const owned = projects.filter(p => p.sectorId === id);
  if (owned.length > 0) {
    return {
      ok: false,
      reason: 'has-dependents',
      blockers: [`${owned.length} project(s)`],
    };
  }

  const remaining = list.filter(s => s.id !== id);
  // Close the gap so ordering stays contiguous within the parent company.
  const resequenced = remaining.map(s =>
    s.companyId === target.companyId && s.order > target.order
      ? { ...s, order: s.order - 1 }
      : s);

  writeSectors(resequenced);
  return { ok: true, record: target };
}

/**
 * Moves a sector up or down within its company.
 *
 * Ordering is per-company and always contiguous from 0. A move past either
 * end is a no-op returning ok:true — the user asked for something already
 * true, which is not an error.
 */
/**
 * Archives a sector.
 *
 * SPRINT 2. Same reasoning as `archiveCompany`: 'Archived' was a legal
 * `EntityStatus` with no way to reach it.
 *
 * Refused while ACTIVE (non-archived) projects still sit in the sector,
 * because hiding the parent would strand them in the project picker with
 * no visible sector. `projects` is passed in rather than read here — the
 * project store is owned by projectMaster, and reaching across would give
 * this module two sources of truth for the same fact.
 *
 * The sector keeps its `projectIds` cache untouched, so restoring it
 * brings back exactly the same membership.
 */
export function archiveSector(
  id: string, projects: ProjectLink[] = [], by = 'unknown', note = '',
): MdResult<Sector> {
  const list = readSectors();
  const i = list.findIndex(s => s.id === id);
  if (i < 0) return { ok: false, reason: 'not-found' };
  if (list[i].status === 'Archived') {
    return { ok: false, reason: 'already-archived', record: list[i] };
  }

  // `status` now travels on ProjectLink. Absent is read as ACTIVE, which
  // is the conservative reading: an unknown project should block an
  // archive rather than be silently ignored.
  const live = projects.filter(
    p => p.sectorId === id && p.status !== 'Archived',
  );
  if (live.length > 0) {
    return {
      ok: false,
      reason: 'has-active-children',
      blockers: [`${live.length} active project(s)`],
    };
  }

  const at = new Date().toISOString();
  const next: Sector = {
    ...list[i],
    status: 'Archived',
    archivedAt: at,
    archivedBy: by || 'unknown',
    archiveLog: [
      ...(list[i].archiveLog || []),
      { action: 'archived', at, by: by || 'unknown', note: String(note || '') },
    ],
  };
  const out = list.slice();
  out[i] = next;
  writeSectors(out);
  return { ok: true, record: next };
}

/**
 * Restores an archived sector.
 *
 * Refused when the parent company is itself archived — restoring a child
 * under a hidden parent produces exactly the orphan state the archive
 * guards exist to prevent. Restore the company first.
 */
export function restoreSector(id: string, by = 'unknown', note = ''): MdResult<Sector> {
  const list = readSectors();
  const i = list.findIndex(s => s.id === id);
  if (i < 0) return { ok: false, reason: 'not-found' };
  if (list[i].status !== 'Archived') {
    return { ok: false, reason: 'not-archived', record: list[i] };
  }

  const parent = findCompanyById(list[i].companyId);
  if (parent && parent.status === 'Archived') {
    return {
      ok: false,
      reason: 'has-active-children',
      blockers: [`parent company "${parent.name}" is archived — restore it first`],
    };
  }

  // The archive EVENT survives the restore. Only the current-state
  // fields are cleared, because a restored sector is not archived.
  const log = (list[i].archiveLog || []).slice();
  if (log.length === 0 && list[i].archivedAt) {
    log.push({ action: 'archived', at: list[i].archivedAt as string,
               by: list[i].archivedBy || 'unknown', note: '' });
  }
  log.push({ action: 'restored', at: new Date().toISOString(), by: by || 'unknown', note: String(note || '') });

  const { archivedAt, archivedBy, ...rest } = list[i];
  const next: Sector = { ...rest, status: 'Active', archiveLog: log };
  const out = list.slice();
  out[i] = next;
  writeSectors(out);
  return { ok: true, record: next };
}

/** Sectors of one company excluding archived. */
export function activeSectorsOf(companyId: string): Sector[] {
  return readSectors()
    .filter(s => s.companyId === companyId && s.status !== 'Archived')
    .sort((a, b) => a.order - b.order);
}

export function reorderSector(id: string, direction: 'up' | 'down'): MdResult<Sector> {
  const list = readSectors();
  const target = list.find(s => s.id === id);
  if (!target) return { ok: false, reason: 'not-found' };

  const siblings = list
    .filter(s => s.companyId === target.companyId)
    .sort((a, b) => a.order - b.order);

  const pos = siblings.findIndex(s => s.id === id);
  const swapWith = direction === 'up' ? pos - 1 : pos + 1;
  if (swapWith < 0 || swapWith >= siblings.length) {
    return { ok: true, record: target };
  }

  const a = siblings[pos];
  const b = siblings[swapWith];
  const out = list.map(s => {
    if (s.id === a.id) return { ...s, order: b.order };
    if (s.id === b.id) return { ...s, order: a.order };
    return s;
  });

  writeSectors(out);
  return { ok: true, record: { ...a, order: b.order } };
}

/** Explicit ordering for a whole company, e.g. after a drag. */
export function setSectorOrder(companyId: string, orderedIds: string[]): MdResult<Sector[]> {
  const list = readSectors();
  const siblings = list.filter(s => s.companyId === companyId);
  if (siblings.length !== orderedIds.length) return { ok: false, reason: 'invalid-order' };
  if (!siblings.every(s => orderedIds.includes(s.id))) return { ok: false, reason: 'invalid-order' };

  const rank = new Map(orderedIds.map((id, i) => [id, i]));
  const out = list.map(s =>
    s.companyId === companyId ? { ...s, order: rank.get(s.id) ?? s.order } : s);
  writeSectors(out);
  return { ok: true };
}

// ── RECONCILIATION ─────────────────────────────────────────────────────

export interface ReconcileReport {
  /** Projects with no company or no sector. */
  orphanProjects: string[];
  /** Sectors whose companyId points at nothing. */
  orphanSectors: string[];
  /** Projects whose sectorId points at nothing. */
  danglingSector: string[];
  /** Projects whose companyId disagrees with their sector's company. */
  mismatched: string[];
  /** projectIds entries that no longer correspond to a real project. */
  staleLinks: number;
  /** True when the cached projectIds needed rewriting. */
  repaired: boolean;
}

/**
 * Rebuilds `Sector.projectIds` from the projects array and reports every
 * integrity violation found on the way.
 *
 * DERIVED, NOT AUTHORITATIVE. `Project.sectorId` is the truth; this only
 * refreshes the cache the older call sites read. Nothing is deleted and no
 * project is reassigned — a mismatch is REPORTED so a human can decide,
 * because silently moving a project between companies would be exactly the
 * kind of invisible data change this platform refuses to make.
 */
export function reconcile(projects: ProjectLink[]): ReconcileReport {
  const companies = readCompanies();
  const sectors = readSectors();
  const companyIds = new Set(companies.map(c => c.id));
  const sectorById = new Map(sectors.map(s => [s.id, s]));
  const projectIds = new Set(projects.map(p => p.id));

  const orphanProjects: string[] = [];
  const danglingSector: string[] = [];
  const mismatched: string[] = [];

  const bySector = new Map<string, string[]>();

  projects.forEach(p => {
    if (!p.sectorId || !p.companyId) { orphanProjects.push(p.id); return; }
    const sec = sectorById.get(p.sectorId);
    if (!sec) { danglingSector.push(p.id); return; }
    if (sec.companyId !== p.companyId) mismatched.push(p.id);
    bySector.set(p.sectorId, [...(bySector.get(p.sectorId) ?? []), p.id]);
  });

  const orphanSectors = sectors
    .filter(s => !companyIds.has(s.companyId))
    .map(s => s.id);

  // Count cached links that point at projects which no longer exist.
  let staleLinks = 0;
  sectors.forEach(s => {
    s.projectIds.forEach(pid => { if (!projectIds.has(pid)) staleLinks++; });
  });

  const nextSectors = sectors.map(s => ({
    ...s,
    projectIds: bySector.get(s.id) ?? [],
  }));

  const changed = JSON.stringify(sectors.map(s => s.projectIds))
    !== JSON.stringify(nextSectors.map(s => s.projectIds));
  if (changed) writeSectors(nextSectors);

  // Refresh the presentation counters on the company records.
  const countsChanged = refreshCompanyCounts(nextSectors, projects);

  return {
    orphanProjects,
    orphanSectors,
    danglingSector,
    mismatched,
    staleLinks,
    repaired: changed || countsChanged,
  };
}

/** Keeps `company.sectors` / `company.projects` honest. Presentation only. */
function refreshCompanyCounts(sectors: Sector[], projects: ProjectLink[]): boolean {
  const list = readCompanies();
  const next = list.map(c => {
    const secs = sectors.filter(s => s.companyId === c.id);
    const projCount = projects.filter(p => p.companyId === c.id).length;
    return { ...c, sectors: secs.length, projects: projCount };
  });
  const changed = JSON.stringify(list) !== JSON.stringify(next);
  if (changed) writeCompanies(next);
  return changed;
}

// ── VALIDATION ─────────────────────────────────────────────────────────

export interface ValidationIssue {
  level: 'error' | 'warning';
  code:
    | 'orphan-project' | 'orphan-sector' | 'dangling-sector'
    | 'company-mismatch' | 'duplicate-company-id' | 'duplicate-sector-id'
    | 'duplicate-project-id' | 'duplicate-company-name'
    | 'duplicate-sector-name' | 'missing-name';
  message: string;
  ids: string[];
}

/**
 * Full referential sweep. Read-only — never repairs, only reports.
 *
 * `error` means the data is inconsistent and a screen will misbehave.
 * `warning` means it is legal but suspicious.
 */
export function validateMasterData(projects: ProjectLink[] = []): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  const companies = readCompanies();
  const sectors = readSectors();

  const push = (level: ValidationIssue['level'], code: ValidationIssue['code'],
                message: string, ids: string[]) => {
    if (ids.length) issues.push({ level, code, message, ids });
  };

  // ── Duplicate ids ──
  const dupIds = (arr: { id: string }[]) => {
    const seen = new Set<string>(); const dup = new Set<string>();
    arr.forEach(x => { if (seen.has(x.id)) dup.add(x.id); seen.add(x.id); });
    return Array.from(dup);
  };
  push('error', 'duplicate-company-id', 'Duplicate company id', dupIds(companies));
  push('error', 'duplicate-sector-id', 'Duplicate sector id', dupIds(sectors));
  push('error', 'duplicate-project-id', 'Duplicate project id', dupIds(projects));

  // ── Duplicate names inside the same parent ──
  const dupCompanyNames = new Set<string>();
  companies.forEach((c, i) => {
    if (companies.some((o, j) => j !== i && sameName(o.name, c.name))) {
      dupCompanyNames.add(c.name);
    }
  });
  push('error', 'duplicate-company-name',
       'Two companies share a name', Array.from(dupCompanyNames));

  const dupSectorNames: string[] = [];
  const byCompany = new Map<string, Sector[]>();
  sectors.forEach(s => byCompany.set(s.companyId, [...(byCompany.get(s.companyId) ?? []), s]));
  byCompany.forEach((group, cid) => {
    group.forEach((s, i) => {
      if (group.some((o, j) => j !== i && sameName(o.name, s.name))) {
        dupSectorNames.push(`${cid}/${s.name}`);
      }
    });
  });
  push('error', 'duplicate-sector-name',
       'Two sectors share a name inside one company', Array.from(new Set(dupSectorNames)));

  // ── Missing names ──
  push('error', 'missing-name', 'Record has no name', [
    ...companies.filter(c => !c.name.trim()).map(c => c.id),
    ...sectors.filter(s => !s.name.trim()).map(s => s.id),
  ]);

  // ── Referential integrity ──
  const companyIds = new Set(companies.map(c => c.id));
  const sectorById = new Map(sectors.map(s => [s.id, s]));

  push('error', 'orphan-sector', 'Sector points at a company that does not exist',
       sectors.filter(s => !companyIds.has(s.companyId)).map(s => s.id));

  push('error', 'orphan-project', 'Project has no company or no sector',
       projects.filter(p => !p.companyId || !p.sectorId).map(p => p.id));

  push('error', 'dangling-sector', 'Project points at a sector that does not exist',
       projects.filter(p => p.sectorId && !sectorById.has(p.sectorId)).map(p => p.id));

  push('error', 'company-mismatch',
       "Project's company disagrees with its sector's company",
       projects.filter(p => {
         if (!p.sectorId || !p.companyId) return false;
         const s = sectorById.get(p.sectorId);
         return !!s && s.companyId !== p.companyId;
       }).map(p => p.id));

  return issues;
}

/** Convenience: true when nothing is broken. */
export function isMasterDataValid(projects: ProjectLink[] = []): boolean {
  return validateMasterData(projects).every(i => i.level !== 'error');
}

// ── Name resolution helpers ────────────────────────────────────────────

/** Display name for a company id, or a dash. Never invents a name. */
export function companyNameOf(id: string, lang: 'en' | 'ar' = 'en'): string {
  const c = findCompanyById(id);
  if (!c) return '—';
  return (lang === 'ar' && c.nameAr) ? c.nameAr : c.name;
}

/** Display name for a sector id, or a dash. */
export function sectorNameOf(id: string, lang: 'en' | 'ar' = 'en'): string {
  const s = findSectorById(id);
  if (!s) return '—';
  return (lang === 'ar' && s.nameAr) ? s.nameAr : s.name;
}


// ── Currency resolution across the hierarchy ───────────────────────────

/**
 * The company's reporting currency — Task 4/5.
 *
 * Reads the FX store, which is the AUTHORITY every conversion uses, and
 * falls back to the mirror on the Company record only when the FX store
 * has no entry yet. Returns '' rather than guessing 'SAR': a caller that
 * needs a default should say so explicitly, because a silent SAR is
 * precisely the defect Phase 3E traced through six modules.
 */
export function reportingCurrencyOfCompany(companyId: string): string {
  if (!companyId) return '';
  try {
    const raw = JSON.parse(localStorage.getItem(`pactum-currency-${companyId}`) || 'null');
    const base = String(raw?.baseCurrency ?? '').toUpperCase().slice(0, 3);
    if (base) return base;
  } catch { /* fall through to the mirror */ }
  return findCompanyById(companyId)?.reportingCurrency ?? '';
}

/**
 * The contract currency a NEW project in this sector should default to.
 *
 * Sector default first, then the company's reporting currency. Used only
 * to pre-fill the create form — the user may still override, and an
 * existing project is never affected.
 */
export function defaultContractCurrencyFor(
  companyId: string, sectorId?: string,
): string {
  const sec = sectorId ? findSectorById(sectorId) : undefined;
  return sec?.defaultContractCurrency || reportingCurrencyOfCompany(companyId);
}
