import React, { useState } from 'react';
import { Company } from '../types';
import { CURRENCY_SEED } from '../../../lib/currency';
import { CALENDARS } from '../../../lib/masterData';
import { AlertTriangle } from 'lucide-react';

/**
 * Create Company wizard.
 * Destination: src/features/company-management/components/CompanyWizard.tsx
 *
 * ══════════════════════════════════════════════════════════════════════
 * PATCH — three defects, all measured before changing anything.
 *
 * 1 · REPORTING CURRENCY WAS NEVER COLLECTED
 *
 *     `finish()` built the company from 13 fields and reportingCurrency
 *     was not one of them. Phase 3F made it mandatory on the registry,
 *     so every company created here was refused:
 *
 *       created : 0
 *       reason  : missing-currency
 *       "Company A" was not saved: a reporting currency is required.
 *
 *     Company creation through this modal was therefore impossible.
 *
 * 2 · BLANK NAME BECAME AN AUTOGENERATED PLACEHOLDER
 *
 *       name: form.name || 'New Company'
 *
 *     A user who left the field empty got a company literally called
 *     "New Company" — measured, and it persisted under that name.
 *
 *     The registry REFUSES a blank name. This line defeated that by
 *     inventing one before the registry ever saw it, which is precisely
 *     the "no autogenerated placeholder" rule the audits check. The fix
 *     is not a better default — it is no default. The Create button
 *     stays disabled until a real name is typed.
 *
 * 3 · `country: form.country || 'Unknown'`
 *
 *     Same shape, on a field this wizard's own label already marks
 *     "(required)". Also removed; the step cannot advance without it.
 *
 * ── What did NOT change ───────────────────────────────────────────────
 *
 *   The 4-step shape, the styling, the props contract and `onCreate`
 *   are untouched. Step 2 gains the currency/locale fields; every other
 *   step is as it was.
 * ══════════════════════════════════════════════════════════════════════
 */

interface Props {
  onCreate: (c: Company) => void;
  onCancel?: () => void;
}

export default function CompanyWizard({ onCreate, onCancel }: Props) {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<any>({
    name: '', nameAr: '', code: '', description: '',
    logoUrl: undefined, primaryColor: '#D4AF5A', secondaryColor: '#333333',
    initCreateSector: false,
    // location
    country: '', city: '', headquarters: '',
    // reporting — mandatory, see note 1 above
    reportingCurrency: '', timeZone: '', calendar: '',
  });

  const next = () => setStep(s => Math.min(4, s + 1));
  const prev = () => setStep(s => Math.max(0, s - 1));

  const handleFile = (f?: File) => {
    if (!f) { setForm((p: any) => ({ ...p, logoUrl: undefined })); return; }
    const r = new FileReader();
    r.onload = () => setForm((p: any) => ({ ...p, logoUrl: String(r.result) }));
    r.readAsDataURL(f);
  };

  // ── Gates ──
  // A step cannot be left until what it asks for is actually present.
  // Nothing is substituted on the user's behalf.
  const nameOk = String(form.name || '').trim().length > 0;
  const countryOk = String(form.country || '').trim().length > 0;
  const currencyOk = /^[A-Za-z]{3}$/.test(String(form.reportingCurrency || '').trim());

  const stepOk =
    step === 0 ? (nameOk && countryOk)
    : step === 2 ? currencyOk
    : true;

  const canCreate = nameOk && countryOk && currencyOk;

  const finish = () => {
    if (!canCreate) return;
    const company: Company = {
      id: `c_${Date.now()}`,
      // No `|| 'New Company'`. A blank name cannot reach here.
      name: String(form.name).trim(),
      nameAr: String(form.nameAr || '').trim() || undefined,
      logoUrl: form.logoUrl,
      status: 'Active',
      portfolioValue: 0,
      sectors: form.initCreateSector ? 1 : 0,
      projects: 0,
      riskRating: 'Low',
      compliance: 'Compliant',
      // No `|| 'Unknown'`. The field is gated above.
      country: String(form.country).trim(),
      city: String(form.city || '').trim() || undefined,
      headquarters: String(form.headquarters || '').trim() || undefined,
      // The field whose absence blocked every create.
      reportingCurrency: String(form.reportingCurrency).trim().toUpperCase(),
      timeZone: String(form.timeZone || '').trim() || undefined,
      calendar: form.calendar || undefined,
      description: String(form.description || '').trim() || undefined,
      primaryColor: form.primaryColor,
      secondaryColor: form.secondaryColor,
      createdAt: '',
      createdBy: '',
    } as Company;
    onCreate(company);
  };

  const field = 'w-full bg-black/10 border border-white/[0.06] px-3 py-2 text-white';
  const label = 'text-[12px] text-white/30';

  return (
    <div className="p-3">
      <div className="mb-4">
        <div>
          <div className="text-white font-semibold">
            Create Company — Step {step + 1} of 5
            <span className="ms-2 text-[12px] font-normal text-white/40">
              {['Identity', 'Branding', 'Reporting currency', 'Initial sector', 'Review'][step]}
            </span>
          </div>
          {/*
            The steps, named and shown.

            "Step 1 of 5" told the user how far along they were and nothing
            about what was still coming. Reporting currency is REQUIRED and
            lives on step 3 of a scrolling modal, so it was easy to walk
            past — and the failure only surfaced afterwards, as a banner on
            a page with no field to fix it on. Naming the steps, and marking
            the required one that is not yet satisfied, puts the demand in
            front of the user before it becomes an error.
          */}
          <div className="flex items-center gap-1.5 mt-1.5">
            {[0, 1, 2, 3, 4].map(i => {
              const needed = i === 2 && !currencyOk;
              return (
                <span
                  key={i}
                  title={['Identity', 'Branding', 'Reporting currency (required)', 'Initial sector', 'Review'][i]}
                  className={
                    'h-1 w-8 ' +
                    (i === step ? 'bg-primary'
                     : needed ? 'bg-amber-500/60'
                     : i < step ? 'bg-primary/40' : 'bg-white/10')
                  }
                />
              );
            })}
            {!currencyOk && (
              <span className="ms-2 text-[11px] text-amber-400">
                Reporting currency still required
              </span>
            )}
          </div>
        </div>
      </div>

      {step === 0 && (
        <div className="grid grid-cols-1 gap-3">
          <label className={label}>English name (required)</label>
          <input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className={field} />
          <label className={label}>Arabic name</label>
          <input value={form.nameAr} onChange={e => setForm({ ...form, nameAr: e.target.value })} className={field} />
          <label className={label}>Company code</label>
          <input value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} className={field} />
          <label className={label}>Description</label>
          <textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className={field} />

          <label className={label}>Country (required)</label>
          <input value={form.country} onChange={e => setForm({ ...form, country: e.target.value })} className={field} />
          <label className={label}>City (optional)</label>
          <input value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} className={field} />
          <label className={label}>Headquarters (optional)</label>
          <input value={form.headquarters} onChange={e => setForm({ ...form, headquarters: e.target.value })} className={field} />

          {!stepOk && (
            <div className="flex items-start gap-2 border border-amber-500/30 bg-black/20 px-3 py-2">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-400 mt-0.5 flex-shrink-0" />
              <span className="text-[12px] text-amber-400">
                An English name and a country are required. Neither is filled in for you.
              </span>
            </div>
          )}
        </div>
      )}

      {step === 1 && (
        <div className="grid grid-cols-1 gap-3">
          <label className={label}>Logo</label>
          <input type="file" accept="image/*" onChange={e => handleFile(e.target.files?.[0])} className="text-white/40" />
          {form.logoUrl && <img src={form.logoUrl} alt="logo" className="w-20 h-20 object-contain border border-white/[0.04] mt-2" />}
          <label className={label + ' mt-2'}>Primary color</label>
          <input type="color" value={form.primaryColor} onChange={e => setForm({ ...form, primaryColor: e.target.value })} className="w-16 h-8 p-0" />
          <label className={label}>Secondary color</label>
          <input type="color" value={form.secondaryColor} onChange={e => setForm({ ...form, secondaryColor: e.target.value })} className="w-16 h-8 p-0" />
        </div>
      )}

      {/* ── Reporting — the step whose absence blocked every create ── */}
      {step === 2 && (
        <div className="grid grid-cols-1 gap-3">
          <label className={label}>Reporting currency (required)</label>
          <select
            value={form.reportingCurrency}
            onChange={e => setForm({ ...form, reportingCurrency: e.target.value })}
            className={field + ' font-mono'}
          >
            <option value="">Select a reporting currency…</option>
            {CURRENCY_SEED.filter(c => c.active).map(c => (
              <option key={c.code} value={c.code}>{c.code} — {c.name}</option>
            ))}
          </select>
          <p className="text-[12px] text-white/30">
            Every converted figure for this company lands in this currency. It belongs to the
            company, not to its projects — a project keeps its own contract currency.
          </p>

          <label className={label + ' mt-2'}>Time zone (optional)</label>
          <input
            value={form.timeZone}
            onChange={e => setForm({ ...form, timeZone: e.target.value })}
            placeholder="Asia/Riyadh"
            className={field + ' font-mono'}
          />

          <label className={label}>Working calendar (optional)</label>
          <select
            value={form.calendar}
            onChange={e => setForm({ ...form, calendar: e.target.value })}
            className={field}
          >
            <option value="">Not set</option>
            {CALENDARS.map(c => (
              <option key={c.value} value={c.value}>{c.en}</option>
            ))}
          </select>
          <p className="text-[12px] text-white/30">
            Time zone and calendar are recorded for reference. Neither enters a delay or
            earned-value calculation.
          </p>

          {!stepOk && (
            <div className="flex items-start gap-2 border border-amber-500/30 bg-black/20 px-3 py-2">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-400 mt-0.5 flex-shrink-0" />
              <span className="text-[12px] text-amber-400">
                A reporting currency is required. Without one the company cannot be saved.
              </span>
            </div>
          )}
        </div>
      )}

      {step === 3 && (
        <div>
          <label className="flex items-center gap-2">
            <input type="checkbox" checked={form.initCreateSector} onChange={e => setForm({ ...form, initCreateSector: e.target.checked })} />
            <span className="text-[13px] text-white/40">Create an initial sector for this company</span>
          </label>
        </div>
      )}

      {step === 4 && (
        <div>
          <p className="text-white/40">Finish and create the company. You can edit details later in Company Management.</p>
          <div className="mt-3 text-white/30 text-sm">Name: {form.name || '—'}</div>
          <div className="text-white/30 text-sm">Code: {form.code || '—'}</div>
          <div className="text-white/30 text-sm">Country: {form.country || '—'}</div>
          <div className="text-white/30 text-sm">
            Reporting currency: <span className="font-mono text-primary">{form.reportingCurrency || '—'}</span>
          </div>
          {!canCreate && (
            <div className="mt-3 flex items-start gap-2 border border-amber-500/30 bg-black/20 px-3 py-2">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-400 mt-0.5 flex-shrink-0" />
              <span className="text-[12px] text-amber-400">
                {!nameOk && 'An English name is required. '}
                {!countryOk && 'A country is required. '}
                {!currencyOk && 'A reporting currency is required. '}
                Go back and complete it — nothing is filled in for you.
              </span>
            </div>
          )}
        </div>
      )}

      <div className="mt-4 flex items-center gap-2">
        <button onClick={prev} disabled={step === 0} className="px-3 py-2 border border-white/[0.06] text-white/40 disabled:opacity-40">Back</button>
        {step < 4 ? (
          <button
            onClick={next}
            disabled={!stepOk}
            className="px-4 py-2 bg-primary text-black font-bold disabled:opacity-40 disabled:pointer-events-none"
          >
            Next
          </button>
        ) : (
          <button
            onClick={finish}
            disabled={!canCreate}
            className="px-4 py-2 bg-primary text-black font-bold disabled:opacity-40 disabled:pointer-events-none"
          >
            Create Company
          </button>
        )}
        <button onClick={onCancel} className="px-3 py-2 border border-white/[0.06] text-white/40">Cancel</button>
      </div>
    </div>
  );
}
